name: Windows (x64)

on:
  push:
    tags:
      - 'v*'  # 当推送以 v 开头的 tag 时触发

# 添加权限设置
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 240  # 设置超时时间为4个小时
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整的 git 历史

    - name: Build
      shell: cmd
      run: call ./windows.bat

    - name: Compress v8 Directory
      shell: pwsh
      run: |
        Compress-Archive -Path v8\* -DestinationPath v8_out.zip -Force

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: |
          ## 更新内容
          - 自动构建的 V8 引擎
          - 构建时间: ${{ steps.date.outputs.date }}
          - 触发 Tag: ${{ github.ref_name }}

    - name: Upload v8_out.zip to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./v8_out.zip
        asset_name: v8_windows_x64_${{ github.ref_name }}.zip
        asset_content_type: application/zip
