name: Windows (x64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      shell: cmd
      run: call ./windows.bat

    - name: Compress v8 Directory
      run: |
        Compress-Archive -Path v8\* -DestinationPath v8_out.zip -Force
      shell: pwsh

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload v8_out.zip to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./v8_out.zip
        asset_name: v8_out.zip
        asset_content_type: application/zip